#!/bin/bash
# Fantasy Football AI Project Cleanup Script
# Generated automatically - review before running

set -e  # Exit on error

cd '/Users/christopherbratkovics/Desktop/fantasy-football-ai'

echo 'Starting Fantasy Football AI project cleanup...'

rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/__pycache__/__init__.cpython-311.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/quality/__pycache__/anomaly_detector.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/quality/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/__pycache__/orchestrator.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/__pycache__/rate_limiter.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/__pycache__/priority_queue.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/__pycache__/etl.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/__pycache__/__init__.cpython-311.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/simple_database.cpython-311.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/simple_database.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/models.cpython-311.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/models.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/database.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/__init__.cpython-311.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/storage/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/sources/__pycache__/nfl_comprehensive.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/core/data/sources/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/models/__pycache__/ml_integration.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/models/__pycache__/feature_engineering.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/models/__pycache__/gmm_clustering.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/models/__pycache__/neural_network.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/models/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/__pycache__/__init__.cpython-311.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/cli/__pycache__/cli_commands.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/src/fantasy_ai/cli/__pycache__/__init__.cpython-310.pyc'
rm '/Users/christopherbratkovics/Desktop/fantasy-football-ai/fantasy_ai.log'
mkdir -p '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/populate_test_data.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/populate_test_data.py'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/test_basic.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/test_basic.py'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/dev/test_nfl_api.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/test_nfl_api.py'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/dev/quick_fix_test.sh' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/quick_fix_test.sh'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/dev/proper_api_flow_test.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/proper_api_flow_test.py'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/dev/minimal_db_test.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/minimal_db_test.py'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/dev/debug_nfl_api.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/debug_nfl_api.py'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/dev/debug_test.py' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/tests/debug_test.py'
mkdir -p '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.working' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.working'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.broken' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.broken'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.backup' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.backup'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.bak' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/backups/main.py.bak'
mkdir -p '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/README.md' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/README.md'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/data_dictionary.md' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/data_dictionary.md'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/ARCHITECTURE.md' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/ARCHITECTURE.md'
mv '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/technical_architecture.md' '/Users/christopherbratkovics/Desktop/fantasy-football-ai/docs/technical_architecture.md'

echo 'Cleanup completed!'
echo 'Project structure organized.'
