services:
  postgres:
    image: postgres:15-alpine
    container_name: fantasy_db
    environment:
      POSTGRES_USER: fantasy_user
      POSTGRES_PASSWORD: fantasy_pass
      POSTGRES_DB: fantasy_football
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fantasy_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantasy_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fantasy_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - fantasy_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fantasy_backend
    environment:
      DATABASE_URL: postgresql://fantasy_user:fantasy_pass@postgres:5432/fantasy_football
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-change-in-production
      PYTHONPATH: /app:/app/backend
    volumes:
      - ./backend:/app/backend
      - ./models:/app/models
      - ./api:/app/api
      - ./data:/app/data
      - ./ml:/app/ml
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    networks:
      - fantasy_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fantasy_frontend
    environment:
      API_BASE_URL: http://backend:8000
    volumes:
      - ./frontend:/app
      - ./frontend/.streamlit:/app/.streamlit
    ports:
      - "8501:8501"
    networks:
      - fantasy_network
    depends_on:
      - backend
    command: streamlit run app.py

networks:
  fantasy_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: