# API Configuration
API_BASE_URL = "http://backend:8000" 
API_KEY = "your-api-key-here"

# For local development outside Docker
# API_BASE_URL = "http://localhost:8000"

# Stripe Configuration (for future use)
STRIPE_PUBLIC_KEY = "pk_test_placeholder"

# Other configuration
ENVIRONMENT = "development"
