// Every sentence shown on /decision-lab that is not a value read from the evidence bundle or a
// label rendered from policy_spec.json (see lib/decision-lab/explain.ts). Keep it technical:
// the lab describes evidence, assumptions and recorded events, nothing else.
import type { Mode } from '@/lib/decision-lab/types'

export const DECISION_LAB_COPY = {
  page: {
    crumb: 'Decision Lab',
    eyebrow: 'One slot · committed evidence · offline',
    lede:
      'A one-slot start/sit comparison over the committed evidence bundle served from this origin: no hosted API, no warehouse, no live feed, no model loading in the browser. It is not a lineup optimizer, a draft engine or a game-day service, and it makes no promise about winning a league. Every recommendation is conditional on the assumptions you record, and every recorded choice stays in this browser until you export it.',
  },

  contexts: {
    historical_replay: {
      label: 'Historical replay',
      is: 'Recorded retrospective evaluation rows with observed outcomes in a separate file.',
      isNot: 'Not proof of what anyone knew before kickoff; the population is players who appear in realized stats.',
    },
    published_weekly: {
      label: 'Published weekly snapshot',
      is: 'The newest published projection artifact with its data cutoff, generation time and run id.',
      isNot: 'Not current, live or game-day verified; availability is a user assumption.',
    },
    synthetic: {
      label: 'Synthetic sandbox',
      is: 'Small hand-built inputs for boundary conditions and regression behaviour.',
      isNot: 'Never evidence about any real player and never mixed into historical numbers.',
    },
  } satisfies Record<Mode, { label: string; is: string; isNot: string }>,

  load: {
    loading: 'Verifying the evidence bundle against its manifest…',
    failedTitle: 'The evidence bundle could not be loaded',
    failedBody:
      'Nothing was substituted, defaulted or partially shown. The loader verifies byte and content digests of every file before using it; a mismatch or a failed fetch stops here.',
    specMismatch:
      'The public bundle was exported with a different policy_spec.json than the one this build evaluates with. Results are computed by this build; rebuild the bundle to remove the difference.',
    specUnchecked: 'The policy specification digest was not checked.',
  },

  library: {
    title: 'Case library',
    help: 'Select a case to load its snapshot, slot, alternatives and parameters. Titles never reveal outcomes.',
    outcomesYes: 'outcomes available',
    outcomesNo: 'no outcomes',
    limitations: 'limitations',
    alternatives: 'alternatives',
    custom: 'Custom nomination',
    customHelp: 'Pick a snapshot from the active context, a slot, and up to eight alternatives.',
  },

  nomination: {
    title: 'Nomination',
    snapshot: 'Snapshot',
    snapshotHelp: 'One source family, season and week from the manifest of the active context.',
    slot: 'Slot',
    slotHelp: 'The slot decides which positions are eligible; FLEX accepts RB, WR and TE.',
    search: 'Find a player',
    searchHelp: 'Filters the loaded snapshot by name, id or team to slot-eligible positions.',
    add: 'Add',
    remove: 'Remove',
    full: 'Eight alternatives is the maximum the policy accepts.',
    none: 'No alternatives nominated yet.',
    noMatches: 'No slot-eligible rows match.',
    loadingSnapshot: 'Loading and verifying the snapshot…',
    availability: 'Availability',
    availabilityHelp:
      'Published rows default to unknown and stay unresolved until you record an explicit assumption. Historical and synthetic rows show the basis the bundle recorded.',
    availabilityDefault: 'Bundle default',
    availabilityAssume: 'I assume available (user-assumed, not verified)',
    availabilityExclude: 'Unavailable (exclude)',
    simulateCorrupt: 'Simulate corrupt evidence',
    simulateCorruptHelp:
      'Marks the snapshot reference as failed integrity for this decision only. The policy answers HOLD and no parameter can unblock it.',
    simulateCorruptDetail: 'simulated integrity failure (synthetic sandbox toggle)',
  },

  parameters: {
    title: 'Parameters',
    minGap: 'Minimum projection gap',
    minGapHelp: 'PPR points between the two leading projections; equality qualifies. 0 to 50.',
    floorEnabled: 'Enable floor guardrail',
    minFloor: 'Minimum floor',
    minFloorHelp: 'The leading option must carry a model floor at or above this value. 0 to 60.',
    requireBaseline: 'Require an independent baseline',
    requireBaselineHelp: 'REVIEW when any comparable alternative lacks a baseline independent of the model.',
    modelOnly: 'Model-only exploration',
    modelOnlyHelp: 'Proceeds without an independent baseline and records that limitation on the result.',
    invalid: 'Enter a finite number inside the allowed range.',
    experiments: 'Experiments from the case',
    experimentsHelp: 'Applies the labelled parameter or availability change and recomputes as a child decision.',
    apply: 'Apply experiment',
    unlock: 'Change an assumption (starts a child decision)',
    frozen: 'Controls are frozen because an action is recorded on this decision. Changing an assumption starts a new child decision that links back to it.',
  },

  note: {
    label: 'Prediction note (optional, written before computing)',
    help: 'Stored on the receipt as text. It cannot be edited once the recommendation is computed.',
    locked: 'Locked with the computed recommendation.',
  },

  compute: {
    button: 'Compute recommendation',
    stale: 'The recommendation is stale for the inputs above — recompute to see a result.',
    empty: 'Select a case from the library or nominate alternatives, then compute a recommendation.',
    needSnapshot: 'Load a snapshot before computing.',
    needAlternatives: 'Nominate at least one alternative before computing.',
    unchanged: 'The inputs are semantically identical to the current decision; its identity did not change.',
  },

  card: {
    title: 'Recommendation',
    unsaved: 'Unsaved exploration',
    recorded: 'Recorded decision',
    noRecommendation: 'No recommendation',
    gap: 'Projection gap',
    threshold: 'threshold',
    floorGate: 'Floor gate',
    floorOff: 'guardrail off',
    floorOk: 'meets',
    floorFail: 'fails',
    floorMissing: 'no floor on the leader',
    baseline: 'Baseline preference',
    baselinePrefers: (name: string, value: string) =>
      `Baseline prefers ${name} (${value}) — a separate comparator, not the model`,
    baselineAgrees: (name: string, value: string) => `Baseline agrees: ${name} (${value})`,
    baselineTie: (value: string) => `Baseline tie at ${value}; it expresses no preference`,
    baselineUnavailable: (who: string) => `Baseline unavailable: no independent baseline for ${who}`,
    limitations: 'Limitations',
    explanation: 'Explanation',
    decisionId: 'Decision id',
    parent: 'Parent decision',
    policy: 'Policy',
  },

  diff: {
    title: 'What changed',
    help: 'The previous result compared with the new one. The new receipt links to the previous decision as its parent.',
    controls: 'Changed controls',
    noneChanged: 'Nothing in the result changed.',
    added: 'reasons added',
    removed: 'reasons removed',
  },

  table: {
    title: 'Alternatives',
    help: 'Ranked by the policy over the comparable set; excluded rows show their reason. Missing values are shown as a dash, never as zero.',
    rank: 'Rank',
    player: 'Player',
    team: 'Team',
    position: 'Pos',
    projection: 'Projection',
    floor: 'Floor',
    ceiling: 'Ceiling',
    baseline: 'Baseline',
    availability: 'Availability',
    comparable: 'Comparable',
    tie: 'Tie',
    excluded: 'excluded',
    yes: 'yes',
    no: 'no',
  },

  action: {
    title: 'Record a choice',
    help: 'The recommendation is never preselected. Every nominated alternative can be chosen, including excluded and non-recommended ones.',
    choose: 'Your choice',
    kind: 'Kind',
    hypothetical: 'Hypothetical replay',
    real: 'Self-reported real choice',
    note: 'Note (optional, up to 500 characters)',
    record: 'Record choice',
    decline: 'Decline to choose',
    needChoice: 'Pick an alternative before recording.',
    recorded: 'Action recorded',
    declined: 'Declined to choose',
    saveFailed: 'The receipt could not be saved',
    notRecommended: 'not recommended',
    excludedLabel: 'excluded',
    recommendedLabel: 'policy recommendation',
  },

  outcome: {
    title: 'Outcomes',
    reveal: 'Reveal outcomes',
    revealHelp:
      'Enabled after a choice is recorded or declined so the sequence is prediction, action, then evidence. The outcome files are static public artifacts and can be inspected at any time; this is educational sequencing, not blinding.',
    loading: 'Loading and verifying the outcome snapshot…',
    none: 'No outcomes are published for this snapshot yet; attach later evidence by importing an updated bundle receipt.',
    failed: 'Outcomes could not be attached',
    idUnchanged: 'Decision id before and after attaching outcomes',
    perAlternative: 'Observed points per alternative',
    notObserved: 'not observed',
    chosen: 'Chosen points',
    regret: 'Complete-choice-set regret',
    vsBaseline: 'Points vs baseline choice',
    modelVsBaseline: 'Model policy vs baseline choice (hypothetical, not attributed to you)',
    coverage: 'Coverage',
    bestInSet: 'Best in choice set',
    sealed: 'Sealed selection pattern of this case',
    attachedAt: 'Attached',
    outcomeId: 'Outcome id',
    reasons: {
      no_action_recorded: 'no action recorded',
      declined: 'declined to choose',
      outcome_missing: 'outcome not observed',
      incomplete_outcomes: 'not every comparable alternative has an observed outcome',
      empty_choice_set: 'no comparable alternatives',
      chosen_outside_choice_set: 'the chosen player is outside the comparable set',
      no_baseline_preference: 'no baseline preference',
      baseline_outcome_missing: 'baseline player outcome not observed',
      no_model_recommendation: 'no model recommendation',
    } as Record<string, string>,
  },

  evidence: {
    title: 'Evidence',
    snapshot: 'Snapshot',
    mode: 'Mode',
    family: 'Source family',
    period: 'Season / week',
    model: 'Model version',
    candidates: 'Candidate per position',
    features: 'Feature version',
    cutoff: 'Data cutoff',
    generated: 'Generated',
    publication: 'Publication',
    population: 'Population',
    exclusions: 'Exclusions',
    coverage: 'Observation coverage',
    baseline: 'Baseline',
    reconciliation: 'Reconciliation',
    sources: 'Source files',
    inputsDigest: 'Inputs content digest',
    decision: 'Decision id',
    policy: 'Policy version',
    revision: 'Export code revision',
    build: 'Bundle build',
    trust: 'Trust boundary',
    evidenceStatus: 'Evidence status',
    noSnapshot: 'No snapshot is loaded.',
  },

  saved: {
    title: 'Saved decisions',
    help: 'Receipts stored in this browser. Export them to keep or replay them elsewhere.',
    empty: 'No saved decisions.',
    open: 'Open',
    attach: 'Attach outcomes',
    delete: 'Delete',
    exportAll: 'Export all',
    import: 'Import',
    clear: 'Clear all',
    confirmDelete: 'Delete this receipt from browser storage?',
    confirmClear: (n: number) => `Remove all ${n} saved receipt(s) from browser storage? Export first if you want to keep them.`,
    imported: 'imported',
    duplicates: 'duplicates',
    rejected: 'rejected',
    problems: 'Storage problems',
    columns: {
      case: 'Case',
      snapshot: 'Snapshot',
      slot: 'Slot',
      status: 'Status',
      recommended: 'Recommended',
      action: 'Action',
      outcome: 'Outcome',
      created: 'Created',
      parent: 'Parent',
    },
    opened: 'Opened a saved receipt; its inputs are shown above and its controls are frozen.',
  },
} as const

export const DECISION_LAB_STATUS_ICON: Record<string, string> = {
  recommend: '▲',
  review: '◆',
  hold: '■',
}
