import type { Metadata } from 'next'
import Link from 'next/link'
import { Suspense } from 'react'
import { Navigation } from '@/components/layout/Navigation'
import { Footer } from '@/components/layout/Footer'
import { DataPlatformExplorer } from '@/components/data-platform/DataPlatformExplorer'
import { PLATFORM_STORIES, WEEKLY_EXAMPLE, repoFile } from '@/content/data-platform'
import { ROUTES } from '@/lib/constants'

export const metadata: Metadata = { title: 'Data Platform | Win My League', description: 'Trace football metrics from grain and SQL through tests, artifacts, APIs, and product.' }

export default function DataPlatformPage() {
  return <div className="portfolio-shell"><Navigation /><main>
    <section className="portfolio-hero !min-h-0"><div className="hero-copy"><div className="eyebrow"><span /> DATA PLATFORM · INSPECTABLE BY DESIGN</div><h1>Question → grain → transformation → test → <em>football product.</em></h1><p className="hero-lede">Python produces predictions and evaluation artifacts. dbt separately turns their file families and statistics into tested player-week facts and versioned decision marts; FastAPI serves both provenance paths without pretending dbt trains the model.</p><div className="hero-actions"><a href="#trace" className="portfolio-button primary">Trace a metric</a><a href="#model-inspector" className="portfolio-button secondary">Inspect models</a></div></div>
      <div className="statement-card dark-card"><span>COMPACT ARCHITECTURE</span><ol className="mt-5 space-y-4">{['nflverse statistics + Python model artifacts','bronze file families → silver quality contracts','gold player-week facts + evaluation/policy marts','Parquet exports → /marts/*; artifacts → /performance','Predictions, Evaluation, Decisions, Player history'].map((x,i)=><li key={x} className="flex gap-3"><b>0{i+1}</b><span>{x}</span></li>)}</ol><p className="mt-5 text-sm">The pre-scoring silver gate and the post-scoring warehouse build are distinct execution stages.</p></div>
    </section>
    <section id="trace" className="case-section scroll-mt-24"><div className="section-heading compact"><div><span className="section-number">02</span><p>TRACE A METRIC</p></div><h2>What share of scored predictions landed within three points?</h2><p>The trace keeps evaluation window, season, model version, candidate and cohort aligned. It never pools ALL with positional cohorts.</p></div>
      <div className="grid gap-4 md:grid-cols-3">{[
        ['1 · INPUT GRAIN','fct_player_week','player_id × season × week × model_version × candidate. Prediction rows without actuals remain visible but do not qualify.'],
        ['2 · TRANSFORMATION','fct_weekly_eval','Rows with actual is not null are aggregated by eval_window × season × week × model_version × candidate × cohort. within_3 is inclusive.'],
        ['3 · PROOF + PRODUCT','independent paths','A singular test reconciles n exactly and MAE/within rates to 0.0001 against evaluation artifacts. /performance serves artifacts; /marts/* serves exports.'],
      ].map(([k,h,p])=><article key={k} className="statement-card"><span>{k}</span><h3><code>{h}</code></h3><p>{p}</p></article>)}</div>
      <article className="mt-6 border border-[#d1d3cd] bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><small>UNIT-TEST EXAMPLE · NOT MEASURED PERFORMANCE</small><h3 className="text-xl font-bold">Inclusive tolerance math</h3></div><a className="font-bold underline" href={repoFile('dbt/models/gold/_gold.yml')} target="_blank" rel="noreferrer">Open fixture</a></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{WEEKLY_EXAMPLE.map(r=><div key={r.error} className="bg-[#f8f7f2] p-3"><b>|error| {r.error}</b><small className="block">within 3: {String(r.within3)} · within 5: {String(r.within5)}</small></div>)}</div><p className="mt-4">The fifth fixture row has no actual and is excluded. Result: n=4, MAE=3.625, within-3=2/4 and within-5=3/4. This defined unit test is not a claim about its most recent execution.</p><div className="mt-4 flex gap-4"><a href={repoFile('dbt/models/gold/fct_weekly_eval.sql')} target="_blank" rel="noreferrer" className="underline">SQL</a><a href={repoFile('dbt/tests/gold/assert_marts_reconcile_to_eval_artifacts.sql')} target="_blank" rel="noreferrer" className="underline">Reconciliation test</a><Link href={`${ROUTES.performance}#decision-policy`} className="underline">Product</Link></div></article>
    </section>
    <section id="decisions" className="case-section"><div className="section-heading compact"><div><span className="section-number">03</span><p>DECISIONS BEHIND THE MODELS</p></div><h2>Tradeoffs remain attached to the implementation.</h2></div><div className="grid gap-5 md:grid-cols-2">{PLATFORM_STORIES.map(s=><article id={s.id} key={s.id} className="statement-card scroll-mt-24"><span>{s.id}</span><h3>{s.title}</h3><p><b>Problem.</b> {s.problem}</p><p><b>Chosen approach.</b> {s.choice}</p><p><b>Tradeoff / limit.</b> {s.tradeoff}</p><p><b>Downstream effect.</b> {s.effect}</p><div className="mt-4 flex flex-wrap gap-4 text-sm font-bold"><Link href={`/data-platform?model=${encodeURIComponent(s.model)}#model-inspector`}>Inspect model</Link><a href={repoFile(s.proof)} target="_blank" rel="noreferrer">Targeted proof</a><a href={repoFile(s.adr)} target="_blank" rel="noreferrer">Decision record</a></div></article>)}</div></section>
    <Suspense fallback={<section className="case-section">Loading model inspector…</section>}><DataPlatformExplorer /></Suspense>
    <section className="case-section"><div className="section-heading compact"><div><span className="section-number">05</span><p>VALIDATE + PUBLISH</p></div><h2>State reuse is not a claim that every test ran.</h2><p>Main builds the full development project. Pull requests may select state:modified+ and defer unchanged nodes to cached main development DuckDB relations; if the cache is unavailable, CI falls back to a full dev build. This is never production deferral. Full-history checks can also be conditional on vars, so a successful workflow is not interchangeable with full-data proof.</p></div><div className="flex flex-wrap gap-4"><a className="underline" href={repoFile('.github/workflows/ci.yml')} target="_blank" rel="noreferrer">CI workflow</a><a className="underline" href={repoFile('docs/adr/0026-slim-ci-deferred-to-cached-main-dev-build.md')} target="_blank" rel="noreferrer">ADR-0026</a><a className="underline" href={repoFile('artifacts/runs/run-20260915T143710Z.json')} target="_blank" rel="noreferrer">Historical run evidence</a></div></section>
  </main><Footer /></div>
}
