/**
 * Loads `tests/fixtures/decision_lab/golden.json` (generated by `python -m ffai.decision_lab.golden
 * --write`) — the shared parity fixture for the Python reference and this TypeScript mirror.
 */
import fs from 'node:fs';
import path from 'node:path';

import type {
  ActionState,
  DecisionInputs,
  DecisionResult,
  OutcomeMetrics,
  OutcomeSnapshot,
  Receipt,
} from '../types';

export interface GoldenCanonicalVector {
  value?: unknown;
  text?: string;
  canonical?: string;
  sha256: string;
}

export interface GoldenPolicyCase {
  name: string;
  inputs: DecisionInputs;
  expected: DecisionResult;
}

export interface GoldenMetricsCase {
  name: string;
  result: DecisionResult;
  action: ActionState;
  outcome_snapshot: { schema_version: string; snapshot_id: string; outcome_id: string; rows: Array<{ player_id: string; actual: number | null }> };
  expected: OutcomeMetrics;
}

export interface GoldenReceipt {
  inputs: DecisionInputs;
  outcome_snapshot: OutcomeSnapshot;
  outcome_id: string;
  receipt_new: Receipt;
  receipt_after_action: Receipt;
  receipt_after_outcome: Receipt;
  receipt_declined: Receipt;
  invariants: { decision_id_unchanged: boolean; result_sha_unchanged: boolean; event_ids: string[] };
}

export interface Golden {
  golden_version: string;
  policy_version: string;
  canonical: GoldenCanonicalVector[];
  policy: GoldenPolicyCase[];
  metrics: GoldenMetricsCase[];
  receipt: GoldenReceipt;
}

export const GOLDEN_PATH = path.resolve(
  __dirname,
  '../../../../../tests/fixtures/decision_lab/golden.json',
);

let cached: Golden | null = null;

/** The parsed golden fixture (read once per test file). */
export function loadGolden(): Golden {
  if (!cached) {
    cached = JSON.parse(fs.readFileSync(GOLDEN_PATH, 'utf8')) as Golden;
  }
  return cached;
}

/** A structural clone so tests can tamper without touching the cached fixture. */
export function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}
